# Generated by Django 5.0.1 on 2026-01-17 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telegram', 'Telegram'), ('proxmox', 'Proxmox'), ('docker', 'Docker'), ('omada', 'Omada/TP-Link')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Enable this integration')),
                ('config_data', models.JSONField(default=dict, help_text='Configuration as JSON')),
                ('last_test', models.DateTimeField(blank=True, help_text='Last test timestamp', null=True)),
                ('last_test_result', models.BooleanField(blank=True, help_text='Last test result', null=True)),
                ('last_test_message', models.TextField(blank=True, help_text='Last test message')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Configuration',
                'verbose_name_plural': 'Integration Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Configuration value')),
                ('description', models.TextField(blank=True, help_text='Description of this setting')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly hostname', max_length=255)),
                ('mac', models.CharField(blank=True, help_text='MAC address', max_length=17, null=True, unique=True)),
                ('vendor', models.CharField(blank=True, help_text='Vendor/OUI', max_length=255, null=True)),
                ('device_type', models.CharField(default='unknown', help_text='Device type', max_length=100)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('nmap', 'Nmap Scan'), ('proxmox', 'Proxmox'), ('docker', 'Docker'), ('omada', 'Omada/TP-Link')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_seen', 'name'],
                'indexes': [models.Index(fields=['mac'], name='inventory_h_mac_20273d_idx'), models.Index(fields=['source'], name='inventory_h_source_1747b2_idx'), models.Index(fields=['is_active'], name='inventory_h_is_acti_d34b0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('assignment', models.CharField(choices=[('dhcp', 'DHCP'), ('static', 'Static'), ('reserved', 'Reserved'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('online', models.BooleanField(default=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='inventory.host')),
            ],
            options={
                'ordering': ['-last_seen', 'ip'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_ip', 'New IP Detected'), ('new_service', 'New Service Detected'), ('host_down', 'Host Down'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='inventory.host')),
                ('related_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='inventory.ipaddress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('proto', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Service name', max_length=255)),
                ('product', models.CharField(blank=True, help_text='Product name', max_length=255)),
                ('version', models.CharField(blank=True, help_text='Version', max_length=255)),
                ('extra_info', models.TextField(blank=True, help_text='Additional info')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='inventory.host')),
            ],
            options={
                'ordering': ['host', 'port', 'proto'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('wifi', 'WiFi'), ('ethernet', 'Ethernet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('ssid', models.CharField(blank=True, help_text='WiFi SSID', max_length=255, null=True)),
                ('switch_port', models.CharField(blank=True, help_text='Switch port', max_length=50, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='inventory.host')),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('host', 'medium', 'ssid')},
            },
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip'], name='inventory_i_ip_70e672_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['assignment'], name='inventory_i_assignm_e73275_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['online'], name='inventory_i_online_3315f0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['type'], name='inventory_a_type_0c5fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='inventory_a_created_fabf5e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['port'], name='inventory_s_port_ca3bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='inventory_s_name_80acbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('host', 'port', 'proto')},
        ),
    ]
