# Generated by Django 5.0.1 on 2026-01-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interfaceattachment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('scan_discovery', 'Discovery Scan (Nmap)'), ('scan_services', 'Service Scan (Nmap)'), ('sync_proxmox', 'Proxmox Sync'), ('sync_docker', 'Docker Sync')], help_text='Task/command name', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the task started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task completed', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', help_text='Task status', max_length=20)),
                ('output', models.TextField(blank=True, help_text='Task output/logs')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('items_processed', models.IntegerField(default=0, help_text='Number of items processed (hosts, services, etc.)')),
            ],
            options={
                'verbose_name': 'Task Execution',
                'verbose_name_plural': 'Task Executions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', '-started_at'], name='inventory_t_task_na_c263e9_idx')],
            },
        ),
    ]
