# Generated by Django 5.0.1 on 2026-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_interfaceattachment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed results/output from the task'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('new_ip', 'New IP Detected'), ('new_service', 'New Service Detected'), ('host_down', 'Host Down'), ('error', 'Error'), ('task_completed', 'Task Completed')], max_length=20),
        ),
    ]
