# Generated by Django 5.0.1 on 2026-01-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_alert_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('new_ip', 'New IP Detected'), ('new_service', 'New Service Detected'), ('host_down', 'Host Down'), ('host_status_change', 'Host Status Changed'), ('error', 'Error'), ('task_completed', 'Task Completed')], max_length=20),
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hostname discovered from scan', max_length=255)),
                ('source_type', models.CharField(default='dns', help_text='Source of hostname: dns, PTR, user, service, script, etc.', max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostnames', to='inventory.host')),
            ],
            options={
                'ordering': ['-last_seen', 'name'],
                'indexes': [models.Index(fields=['host', 'name'], name='inventory_h_host_id_3733ad_idx'), models.Index(fields=['source_type'], name='inventory_h_source__82bef6_idx')],
                'unique_together': {('host', 'name')},
            },
        ),
    ]
