# Generated by Django 5.0.1 on 2026-02-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_host_status_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationconfig',
            options={'ordering': ['name', 'display_name'], 'verbose_name': 'Integration Configuration', 'verbose_name_plural': 'Integration Configurations'},
        ),
        migrations.RenameIndex(
            model_name='hoststatusevent',
            new_name='inventory_h_host_id_aedf12_idx',
            old_name='inventory_h_host_id_7a8b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='hoststatusevent',
            new_name='inventory_h_recorde_580608_idx',
            old_name='inventory_h_recorded_9c4e2a_idx',
        ),
        migrations.AlterField(
            model_name='host',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('nmap', 'Nmap Scan'), ('proxmox', 'Proxmox'), ('docker', 'Docker')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task_name',
            field=models.CharField(choices=[('scan_discovery', 'Discovery Scan (Nmap)'), ('scan_services', 'Service Scan (Nmap)'), ('sync_proxmox', 'Proxmox Sync'), ('sync_docker', 'Docker Sync'), ('sync_adguard', 'AdGuard Home Sync')], help_text='Task/command name', max_length=50),
        ),
    ]
