# Generated by Django 5.0.1 on 2026-02-01 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_integrationconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoststatusevent',
            name='is_snapshot',
            field=models.BooleanField(default=False, help_text='True if recorded as part of a full snapshot (not only changes)'),
        ),
        migrations.AddField(
            model_name='hoststatusevent',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Origin of this observation (scan/sync/manual)', max_length=50),
        ),
        migrations.AddField(
            model_name='hoststatusevent',
            name='task_execution',
            field=models.ForeignKey(blank=True, help_text='TaskExecution that produced this event (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_events', to='inventory.taskexecution'),
        ),
        migrations.AlterField(
            model_name='hoststatusevent',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='hoststatusevent',
            index=models.Index(fields=['source', '-recorded_at'], name='inventory_h_source_b73414_idx'),
        ),
    ]
